formatLog :             "%s: %s"
formatErr :             "%s: %s: %s"
init :                  start initialization
initOk :                initialization ok
initNoOk :              "initialization error: %s"
create :                creating data
read :                  reading data
update :                updating data
delete :                deleting data
createToken :           creating token error
readToken :             reading token error
unmarshal :             unmarshal json
marshal :               marshal json
charWeightOutErr: the weight value is out of range
charGrowthOutErr: the growth value is out of range
charLimitOutErr: you cannot create more than three characters
charGrowthAndWeightOutErr: the growth and the weight values is out of range
writerResponse: writing response body

authStatus :
  busyUsername :    This username is already taken
  invalidUsername : invalid username
  invalidPassword : invalid password
  userNotFound :    Not found
  signIn :          You are sign in
  signUp :          You are sign up
  signOut :         You are sign out
  signAlready : you are already authorized
  passwordUpdated: password updated
  error: error
  noCharacter: no character selected
  accountDeleted: account deleted

cookieName :      AuthenticationKey
badRequest : Bad Request
characterLimit: 3

charStatus :
  charCreate : "the character is created. Id number: %d"
  charCreateLimit : you cannot create more than three characters
  charGet :
  charUpdate : character updated
  charDelete : character deleted
  charAllDelete: all characters deleted
  charNotSelect : no character selected
  charWeightRange: The weight value must be in the range from 40 to 120 kg.
  charGrowthRange: The growth value must be in the range from 145 to 200 cm.
  charHeadListFormat: "List of created characters\n\n"
  charListFormat: "ID: %d\nName: %s\nGrowth: %d cm.\nWeight: %d\n\n"

postgresConnectFormat : "user=%s dbname=%s password=%s sslmode=%s"
driverName :            postgres

actionMsg:
  locationFormat: "\nplace: %s\nweather: %s\ntime: %s\nobstacle: %s\n"
  infoCharFormat: "Information about the selected character:\n\nName: %s\nGrowth: %d cm.\nWeight: %d kg."
  jumpOver: you jumped over!
  jumpFell: you fell

authEndpoints:
  auth: '/auth'
  signIn: '/signIn'
  signUp: '/signUp'
  signOut: '/signOut'
  newPassword: '/newPassword'
  deleteAccount: '/deleteAccount'
apiEndpoints:
  api: '/api'
  createChar: '/createChar'
  getAllChar: '/getAllChar'
  selectChar: '/selectChar'
  updChar: '/updChar'
  delChar: '/delChar'
  delAllChar: '/delAllChar'
actionEndpoints:
  action: '/action'
  infoAboutSelectedChar: '/infoAboutSelectedChar'
  beginActionScene: '/beginActionScene'
  actionScene: '/actionScene'