#enemy generation settings
generationEnemy:
 minQuantityOfEnemies: 1
 maxQuantityOfEnemies: 4 # of 4
 minClassOfEnemy: 1
 maxClassOfEnemy: 4 # of 4
#type of task
typeOfTask:
 location: 5
 locationWithEnemy: 0