# log messages
formatLog :             "%s: %s"
init :                  start initialization
initOk :                initialization ok
initNoOk :              "initialization error: %s"
create :                creating data
read :                  reading data
update :                updating data
delete :                deleting data
createToken :           creating token error
readToken :             reading token error
unmarshal :             unmarshal json
marshal :               marshal json
writerResponse: writing response body
# authorization status messages
authStatus :
  busyUsername :    This username is already taken
  invalidUsername : invalid username
  invalidPassword : invalid password
  userNotFound :    Not found
  signIn :          You are sign in
  signUp :          You are sign up
  signOut :         You are sign out
  signAlready : you are already authorized
  passwordUpdated: password updated
  error: error
  noCharacter: no character selected
  accountDeleted: account deleted
# service messages
charWeightOutErr: the weight value is out of range
charGrowthOutErr: the growth value is out of range
charLimitOutErr: you cannot create more than three characters
charGrowthAndWeightOutErr: the growth and the weight values is out of range
cookieName :      ArchaicReverieKey
badRequest : Bad Request
# user character creation status
charStatus :
  charCreate : "the character is created. Id number: %d"
  charCreateLimit : you cannot create more than three characters
  charGet :
  charUpdate : character updated
  charDelete : character deleted
  charAllDelete: all characters deleted
  charNotSelect : no character selected
  charWeightRange: "The weight value must be in the range from %d to %d kg."
  charGrowthRange: "The growth value must be in the range from %d to %d cm."
  charHeadListFormat: "List of created characters\n\n"
  charListFormat: "ID: %d\nName: %s\nGrowth: %d cm.\nWeight: %d\n\n"
# messages to the player about the results of the character's action
actionMsg:
  locationFormat: "place: %s , weather: %s , time: %s , obstacle: %s"
  infoCharFormat: "Information about the selected character:\n\nName: %s\nGrowth: %d cm.\nWeight: %d kg."
  remainHealth: "You have %d health points left"
  jumpOver: you jumped over!
  jumpFell: you fell!
  invalidSum: invalid sum
  noNeedToRecover: you are full
  invalidFood: invalid food
  invalidWeapon: invalid weapon
  invalidNumberOfWeapons: "You can't have more than %d weapons."
  invalidCommand: invalid command
  lowHP: low health points
  successfulEscape: you escaped!
  failedEscape: you are caught!
  successfulHit: win!
  failedHit: lost!